version: "3.8"
name: business-calendar
services:   
  web-api:
    image: ${DOCKER_REGISTRY-}businesscalendar-webapi
    build:
      context: .
      dockerfile: BusinessCalendar.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "4080:80"