version: "3.8"
name: business-calendar
services:   
  web-api:
    image: ${DOCKER_REGISTRY-}businesscalendar-webapi
    build:
      context: .
      dockerfile: BusinessCalendar.WebAPI/Dockerfile
    environment:
      MongoDB__ConnectionURI: "mongodb://mongodb:27017"
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "4080:80"
    depends_on:
      - mongodb
        
  mongodb:
    image: mongo:6.0.4
    ports:
      - "4081:27017"
    volumes:
      - mongo:/data/db 
        
volumes:
  mongo: