# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    #inputs:
    #  version:
    #    description: 'Version'
    #    #default: '1.0'
    #    required: true
    #    type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout backend
      uses: actions/checkout@v3.5.3
      with: 
        path: backend

    - name: Checkout frontend
      uses: actions/checkout@v3.5.3
      with: 
        repository: 'myzamaraev/business-calendar.dashboard'
        ref: 'master'
        token: ${{ secrets.CHECKOUT_TOKEN }}
        path: frontend

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: v18.16.0
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build frontend
      run: npm run build
      working-directory: ./frontend

    - name: ls working dir
      run: ls frontend
        
    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v2

    #- name: Build and push
    #  uses: docker/build-push-action@v4
    #  with:
    #      context: .
    #      file: ./backend/Dockerfile
    #      load: true
    #      tags: my-base-image:latest

      
    # Runs a single command using the runners shell
    #- name: Send greeting
    #  run: echo "Hello ${{ inputs.version }}"
