name: Publish Client
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version number'
        default: '1.0.0'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: list directory
      run: ls

    - name: Build
      run: dotnet build --configuration Release /p:Version=${{inputs.version}}
      working-directory: ./Src/BusinessCalendar.Client

    - name: pack
      run: dotnet pack --configuration Release /p:Version=${{inputs.version}}
      working-directory: ./Src/BusinessCalendar.Client
      
    - name: push
      run: |
        FILE_PATH="./bin/Release/BusinessCalendar.Client.${{inputs.version}}.nupkg";
        dotnet nuget push $FILE_PATH --api-key "${{ secrets.NUGETORG_APIKEY }}" --source https://api.nuget.org/v3/index.json 
#         --skip-duplicate     
#        dotnet nuget push .nupkg --source https://nuget.pkg.github.com/myzamaraev/index.json --api-key ${{secrets.GITHUB_TOKEN}}
      working-directory: ./Src/BusinessCalendar.Client

      
  
