name: Publish Service
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: "1.0"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout backend
      uses: actions/checkout@v3.5.3
      with: 
        path: backend
        
        
    - name: Run BusinessCalendar.Tests
      run: dotnet test  "./Src/BusinessCalendar.sln" --logger "trx;LogFilePrefix=business-calendar-test-results.trx" --results-directory "TestResults"
      working-directory: ./backend
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure() # run this step even if previous step failed
      with:
        name: BusinessCalendar Tests
        working-directory: ./backend
        path: ./TestResults/*.trx #path to test results
        reporter: dotnet-trx
          
          
    - name: Checkout frontend
      uses: actions/checkout@v3.5.3
      with:
        repository: 'myzamaraev/business-calendar.dashboard'
        ref: 'master'
        token: ${{ secrets.CHECKOUT_TOKEN }}
        path: frontend

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: v18.16.0
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build frontend
      run: npm run build
      working-directory: ./frontend

    - name: ls
      run: ls ./frontend

    - name: Add frontend build to wwwroot
      run: |
        rm ./backend/Src/BusinessCalendar.WebAPI/wwwroot/*
        cp -R ./frontend/dist/* ./backend/Src/BusinessCalendar.WebAPI/wwwroot
        

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./backend/Src
        file: ./backend/Src/BusinessCalendar.WebAPI/Dockerfile
        push: true
        tags: |
          ghcr.io/myzamaraev/businesscalendar:latest
          ghcr.io/myzamaraev/businesscalendar:${{inputs.version}}
