name: Run backend tests
on:
  push:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend
        uses: actions/checkout@v3.5.3
        with:
          path: backend

      - name: Run BusinessCalendar.Tests
        run: dotnet test  "./Src/BusinessCalendar.sln" --logger "trx;LogFilePrefix=business-calendar-test-results" --results-directory "TestResults"
        working-directory: ./backend

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: BusinessCalendar Tests
          working-directory: ./backend
          path: ./TestResults/*.trx #path to test results
          reporter: dotnet-trx
